### PR TITLE
Better Footer

### PR DESCRIPTION
**Pull request by jameswalpole**
@martindale: This PR should remove conflicts from the commit on your branch but will also bring this branch up to date with your latest commits and my own, which add an image to the /about page and modify some language there.

### CODE REVIEW

**Comment by martindale** [comment]
Looks good.  Two nits;

- lots of commits included in this pull request.  Any idea why?
- the last two commits aren't associated with any author.  I'm guessing they were yours, so you might want to `--amend` their author.

**Comment by jameswalpole** [comment]
I may have pulled down all of your master branch’s changes to my own better-footer branch. I’ll check on editing authorship. That’s odd – it’s usually been credited automatically.


James Walpole
jameslwalpole@gmail.com

**Comment by martindale** [comment]
Usually that happens when you change machines or otherwise remove your git configuration.  Just need to follow the [first-time git setup](https://help.github.com/articles/set-up-git/).

I'll investigate the commits (by merging master on your intended destination branch), and then re-apply the authorship information to those commits.  Thanks for the patch!

**Comment by jameswalpole** [comment]
Thanks, Eric!

James Walpole
jameslwalpole@gmail.com

**Comment by martindale** [comment]
Okay, I spent a little time digging into what's going on here.  After going through the commit history, I think our best option would be for you to submit a separate pull request to `master` for 684c524, and then we can simply merge #26 if there aren't any updates to its content.

Mainly, I'm trying to keep each individual pull request limited in scope to changing one thing.  This pull request conflates changes to the about page with changes to the footer, and that's making the commit history muddy and difficult to follow.

**Comment by jameswalpole** [comment]
Copy that. Will do on the morrow.

James Walpole
jameslwalpole@gmail.com

**Pull request closed without merging**
