### PR TITLE
Add images to our contact cards.

### PR DESCRIPTION
**Pull request by martindale**
I pulled each of our Twitter profiles, and I'm adding them as images on our contact cards.  Feel free to submit different photos if you want 'em!

### CODE REVIEW

**Comment by jameswalpole** [comment]
I like it and will merge after confirmation from others. I will follow up with everyone to get the written content to accompany these this weekend

**Comment by martindale** [comment]
@unChaz and @tonysakich report in...

**Comment by unChaz** [comment]
Sorry for the late response. Spent a few days without internet. Mine is fine, although not a good picture, I don't think I have a better alternative.

**Comment by martindale** [comment]
Alright, @tonysakich is the last one – if you agree Tony, go ahead and click merge.  Thanks!

**Comment by tonysakich** [comment]
Looks good to me

**Pull request merged**
